build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - command: phpunit
            coverage:
              file: './coverage.xml'
              format: clover

filter:
  excluded_paths:
    - "tests/"
  dependency_paths:
    - "vendor/"

tools:
  external_code_coverage:
    timeout: 2100 # Timeout in seconds.